FROM golang:1.23.2

RUN apt-get update
RUN apt-get install sudo

# env system
ENV GOPATH /go
ENV PATH $GOPATH/bin:$PATH

# set local time
RUN ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
RUN echo "Asia/Jakarta" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata

ENV TZ=Asia/Jakarta

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN mkdir -p /go/src/app
RUN mkdir -p /go/build

# set working dir
WORKDIR /go/src/app

COPY . .
# Check if go.mod exists, if not initialize Go module
RUN if [ ! -f go.mod ]; then go mod init app && go mod tidy; fi
RUN go get github.com/githubnemo/CompileDaemon
RUN go install github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon -log-prefix=false -build="go build -o /go/src/app/build" -command="/go/src/app/build"
